repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: debug-statements
      - id: end-of-file-fixer
        exclude: "\\.idea/(.)*"
      - id: trailing-whitespace
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: ["--py38-plus"]
  - repo: https://github.com/hadialqattan/pycln
    rev: v2.1.3
    hooks:
      - id: pycln
        args: [--config=pyproject.toml]
  - repo: https://github.com/pycqa/isort
    rev: 5.11.4
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        args: [--config=./pyproject.toml]
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.2
    hooks:
      - id: codespell
  - repo: https://github.com/asottile/blacken-docs
    rev: 1.13.0
    hooks:
      - id: blacken-docs
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0-alpha.4"
    hooks:
      - id: prettier
  - repo: https://github.com/pycqa/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        exclude: "test_*"
        args: ["-iii", "-ll", "-s=B308,B703"]
  - repo: https://github.com/hadialqattan/pycln
    rev: v2.1.3
    hooks:
      - id: pycln
        args: [--config=pyproject.toml]
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.33.0
    hooks:
      - id: markdownlint
        args: [--disable=MD013, --disable=MD033, --disable=MD050]
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          [
            "flake8-bugbear",
            "flake8-comprehensions",
            "flake8-mutable",
            "flake8-print",
            "flake8-simplify",
            "flake8-type-checking",
            "flake8-implicit-str-concat",
            "flake8-noqa",
            "flake8-return",
            "flake8-secure-coding-standard",
            "flake8-encodings",
            "flake8-use-fstring",
            "flake8-use-pathlib",
          ]
  - repo: https://github.com/johnfraney/flake8-markdown
    rev: v0.4.0
    hooks:
      - id: flake8-markdown
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.2.3
    hooks:
      - id: pydocstyle
        exclude: "test*|examples*"
        additional_dependencies:
          - pydocstyle[toml]
  - repo: https://github.com/pycqa/pylint
    rev: "v2.16.0b0"
    hooks:
      - id: pylint
        exclude: "test_*|docs"
        args: ["--unsafe-load-any-extension=y"]
        additional_dependencies: [pydantic, mkdocs_gen_files]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v0.991"
    hooks:
      - id: mypy
        additional_dependencies: [pydantic, mkdocs_gen_files]
